### ISSUE TITLE
all end points 404, even unprotected

### ISSUE THREAD

**Issue by chorsnell** [miguelduarte42/swagger-jwt-example#1]
Doesn't seem to work out of the box. Turned swagger debug on which shows the following:

```
  swagger-tools:middleware:ui GET /api/unprotected +3s
  swagger-tools:middleware:ui   Will process: no +0ms
  swagger-tools:middleware:security GET /api/unprotected +0ms
  swagger-tools:middleware:security   Will process: no +1ms
  swagger-tools:middleware:router GET /api/unprotected +0ms
  swagger-tools:middleware:router   Will process: no +0m
```
when running `node app` the init seems to find the routes ok
```
  swagger-tools:middleware:ui Initializing swagger-ui middleware +0ms
  swagger-tools:middleware:ui   Using swagger-ui from: internal +4ms
  swagger-tools:middleware:ui   API Docs path: /api-docs +2ms
  swagger-tools:middleware:ui   swagger-ui path: /docs +1ms
  swagger-tools:middleware:security Initializing swagger-security middleware +4ms
  swagger-tools:middleware:security   Security handlers: +0ms
  swagger-tools:middleware:security     Bearer +0ms
  swagger-tools:middleware:router Initializing swagger-router middleware +1ms
  swagger-tools:middleware:router   Mock mode: disabled +0ms
  swagger-tools:middleware:router   Controllers: +0ms
  swagger-tools:middleware:router     /home/chris/swagger-jwt-example/api/controllers/main-controller.js: +2ms
  swagger-tools:middleware:router       main-controller_unprotectedGet +0ms
  swagger-tools:middleware:router       main-controller_protectedGet +0ms
  swagger-tools:middleware:router       main-controller_protected2Get +0ms
  swagger-tools:middleware:router       main-controller_loginPost +0ms
```
Either way, doesn't seem to work FYI

**Comment by miguelduarte42** [comment]
Thanks for opening this issue. It should be fixed now, please pull the latest version and try again. I'll also add some basic documentation to the README

**Comment by chorsnell** [comment]
Thanks for getting back so quickly.

It was still having a couple of issue using the built in swagger (on `/docs`) api_key as the barer. It wasn't being pulled through to the auth.js and `token` was `undefined` here
```if (token && token.indexOf("Bearer ") == 0) {```

Made a PR with fixes, and a little addition to the swagger definition: https://github.com/miguelduarte42/swagger-jwt-example/pull/2 :)

**Comment by miguelduarte42** [comment]
Thanks for your contribution! I have merged both PRs.
